filter/pivot.js
package.json
test/filter/pivot.js

This is a transform stream that pivots tags from an array-of-objects to
an object-of-arrays. The latter is usually a more convenient interface
for downstream processors.

Add pivot filter

---

package.json
streams/html.js
test/streams/html.js

Fixes #12
This uses remarkable behind the scenes. Before merge,
I want to figure out how to make the naming of the streams
that
* Output HTML
* Parse Markdown into HTML
* Emit Markdown
Straightforward

Create stream that parses Markdown in JSDoc

---

package.json

Resolves
```
documentation -h
module.js:338
throw err;
^
Error: Cannot find module 'queue-async'
at Function.Module._resolveFilename (module.js:336:15)
at Function.Module._load (module.js:278:25)
at Module.require (module.js:365:17)
at require (module.js:384:17)
at Object.<anonymous> (/Users/deedubs/.npm-packages/lib/node_modules/documentation/streams/output/docset.js:6:11)
at Module._compile (module.js:460:26)
at Object.Module._extensions..js (module.js:478:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Module.require (module.js:365:17)
```

Add `queue-async` to `package.json`

---

share/html/index.hbs
share/html/section.hbs
streams/github.js
streams/hierarchy.js
streams/sort.js
test/fixture/html/nested.output.files

Turned out to be more complicated than I thought, there were four changes:
- sorting was broken (the comparison function was returning true/false instead
of 1, 0, -1)
- the github stream was reversing the order of comments (a bizarre consequence
of calling `resume()` before `push()`)
- the hierarchy stream was reversing the order of members but left the order of
the roots intact
- I moved static members above instance ones (my reasoning being that there are
usually fewer static members and that often they're used for initialization
of new objects so the top is a good place for them)

Fixes for sorting

---

package.json

If the user has a `$HOME/.eslintrc` it will be read and merged with the
`.eslintrc` in this directory; this pull request disables that behavior so that
only the project rules are applied.

Don't run tests with the user's global .eslintrc

---

share/markdown.hbs
streams/output/markdown.js
test/fixture/newline-in-description.input.js
test/fixture/newline-in-description.output.custom.md
test/fixture/newline-in-description.output.json
test/fixture/newline-in-description.output.md

Currently, a newline in a parameter description breaks the default parameters table output.  This is a quick fix for that.

md output: cleanly handle newlines in descriptions.

---

package.json
streams/github.js

It looks like `through` doesn't support asynchronous streams very well. In my
testing it looks like the github stream just stops a third of the way through
processing comments (but with no errors, it just drops the rest on the floor
and you get no output). Substituting `through2` works like a charm, though. :)
Fixes #81

Fix github stream

---

test/fixture/typedef.input.js
test/fixture/typedef.output.custom.md
test/fixture/typedef.output.json
test/fixture/typedef.output.md

@tmcw Added this in a super rudimentary format because I needed it for something. Couple of known issues I didn't have time to examine closely: 1) currently needs a `@name` tag, but presumably the name should be pulled off the `@typedef` tag (right?), and 2) if the typedef comment is at the end of a file, w/ no subsequent code node, it gets dropped.

Add a rudimentary test for @typedef

---

circle.yml
lib/find_git.js
streams/github.js

@HansHammel 
This should address #133 by fixing the path-separator issue that crops up on Windows. Any chance you can test by running this branch?

Test a windows-compatible git finder. Fixes #133

---

bin/documentation.js
index.js
lib/error.js
lib/hierarchy.js
lib/lint.js
lib/nest_params.js
lib/output/json.js
lib/parse.js
test/lib/error.js
test/lib/hierarchy.js
test/lib/lint.js
test/lib/nest_params.js
test/lib/parsers/javascript.js
test/lib/polyglot.js
test/test.js

cc @jfirebaugh @anandthakker for the review
@jfirebaugh re: your comment about functions downstream needing to know about errors that point to invariants... my assumption is that if we hit a showstopper error then we should throw an exception, whereas for 'lint' or handle-able errors we should attach to the comment

Simplify error parsing by attaching errors to comments

---

lib/parsers/javascript.js
test/fixture/trailing-only.input.js
test/fixture/trailing-only.output.custom.md
test/fixture/trailing-only.output.json
test/fixture/trailing-only.output.md
test/fixture/trailing-only.output.md.json
test/fixture/trailing.input.js
test/fixture/trailing.output.custom.md
test/fixture/trailing.output.json
test/fixture/trailing.output.md
test/fixture/trailing.output.md.json

The reason for the two-separate-walks quirk of this code is that comments are attached as _both_ trailing and leading, and we always want to prefer the leading.
cc @jfirebaugh for the review

Walk trailing comments. Fixes #93

---

index.js
lib/html_helpers.js
lib/infer/params.js
test/fixture/es6.output.custom.md
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json
test/fixture/factory.output.custom.md
test/fixture/factory.output.json
test/fixture/factory.output.md
test/fixture/factory.output.md.json
test/fixture/html/nested.output.files
test/fixture/infer-params.input.js
test/fixture/infer-params.output.custom.md
test/fixture/infer-params.output.json
test/fixture/infer-params.output.md
test/fixture/infer-params.output.md.json
test/fixture/multisignature.output.custom.md
test/fixture/multisignature.output.json
test/fixture/multisignature.output.md
test/fixture/multisignature.output.md.json

This uses the AST to add (untyped) params where they aren't explicitly
specified.
Would love to infer types here as well, but espree doesn't support
them yet.
cc @anandthakker / @jfirebaugh for the review

Infer parameters. Fixes #51

---

index.js
lib/input/dependency.js
lib/input/shallow.js
lib/parsers/javascript.js
package.json
test/fixture/bad/syntax.output.json
test/fixture/jsx.input.js
test/fixture/jsx.output.custom.md
test/fixture/jsx.output.json
test/fixture/jsx.output.md
test/fixture/jsx.output.md.json
test/lib/input/shallow.js
test/test.js

Fixes #135 
cc @anandthakker this is the "just parse it again" technique, and I think it works quite well.

Reparse transformed source

---

index.js
lib/flow_doctrine.js
lib/infer/params.js
lib/infer/return.js
test/fixture/flow-types.input.js
test/fixture/flow-types.output.custom.md
test/fixture/flow-types.output.json
test/fixture/flow-types.output.md
test/fixture/flow-types.output.md.json
test/lib/flow_doctrine.js

cc @thejameskyle
cc @jfirebaugh for the review
`lib/flow_doctrine.js` is where we convert Babel-parsed
Flow annotations into doctrine-style objects so they
can be formatted with all of the existing helpers.
As a tail task to this, we'll want to use flow annotations to infer return types as well.

Implement flow type inference for params. Refs #122

---

index.js
lib/infer/membership.js
test/lib/infer/membership.js

Membership inference used to [drop @lends tags](https://github.com/documentationjs/documentation/blob/b9df26fba8afd494ff1d7449821493babfc0c56a/streams/infer/membership.js#L92-L94) as a side effect. Now they make it through the whole chain and produce output even though they aren't meaningful in that way.
This restores the pre-unstream behavior by allowing function elements in the comment pipeline to return undefined to eliminate that comment from further processing.
:eyes: @tmcw

Drop @lends tags during membership inference (fixes #161)

---

lib/hierarchy.js
test/fixture/factory.output.json
test/fixture/newline-in-description.output.json
test/fixture/no-name.output.json
test/fixture/trailing-only.output.json
test/lib/hierarchy.js

This is a pretty big lift:
Refs #111.

Full hierarchy support

---

lib/infer/params.js
test/fixture/nearby_params.input.js
test/fixture/nearby_params.output.custom.md
test/fixture/nearby_params.output.json
test/fixture/nearby_params.output.md
test/fixture/nearby_params.output.md.json

Fixes #191
This a specific exception for the case identified in 191: we could,
instead, include only cases of clear proximity, like var foo = function,
or function foo.
cc @developit

Stop inferring parameters if fn is within a call.

---

lib/output/html.js
lib/resolve_theme.js

Basically the default theme is in the documentation modules node_modules and `resolve` doesn't seem to traverse down and find all of the node_modules directories of all the dependencies, so we have to treat the default as a special case.
Not sure if this is the best way, but it works. Willing to change if there are better options.
Resolves #146

Fix default theme resolve

---

lib/infer/params.js
test/fixture/merge-infered-type.input.js
test/fixture/merge-infered-type.output.custom.md
test/fixture/merge-infered-type.output.json
test/fixture/merge-infered-type.output.md
test/fixture/merge-infered-type.output.md.json

Allow param tag type to be inferred and merged with description

---

lib/args.js
lib/infer/params.js
lib/output/json.js
test/bin.js
test/fixture/partial-default.input.js
test/fixture/partial-default.output.custom.md
test/fixture/partial-default.output.json
test/fixture/partial-default.output.md
test/fixture/partial-default.output.md.json

Some params cannot be identified with only param.name. This
changes the algorithm to transform parameters into doc objects
first, and then using the value of doc.name, which is defined
even for parameters with default values.

Fix type merging. Fixes #233

---

lib/parse.js
test/lib/lint.js
test/lib/parsers/javascript.js

Not all errors are `{message: ...}` objects, [some are plain strings](https://github.com/documentationjs/documentation/compare/lint-format?expand=1#diff-c720f471f49a4909dad9b9fda144eed4L24). 
Fortunately, `vFile#warn` [handles this case for us](https://github.com/wooorm/vfile/blob/master/index.js#L421).
This PR ensures that `format` doesn't throw a runtime exception when passed such an error. 
cc @jfirebaugh @tmcw

Fix exception when formatting string errors

---

lib/args.js
lib/module_filters.js
test/bin.js

add an external option for the cli and permit the use of multiple patterns / globs
in an array. Use micromatch.any() instead of micromatch.matcher()

add an external option

---

index.js
lib/args.js
lib/filter_js.js
test/bin.js
test/fixture/extension/jsx.jsx

This new option change the previous behavior of parsing every input files
from module-deps except json. But if one use browserify to require json file
they may require other file types that cant be supported by documentationjs,
the new behaviour is to parse files whose extension match one in a whitelist
This is a rebased version of #242

Add an extension option

---

index.js
lib/args.js
lib/output/html.js
lib/output/markdown_ast.js
lib/walk.js
test/bin.js
test/fixture/auto_lang_hljs/config.yml
test/fixture/auto_lang_hljs/multilanguage.input.js
test/fixture/auto_lang_hljs/multilanguage.output.md
test/test.js

This is opt-in, hence not a breaking change: make highlightjs recognizing the language of `@example` code snippets.
Please review – your feedback is highly appreciated :smiley:

optional language detection in examples

---

README.md
circle.yml
docs/NODE_API.md
index.js
lib/args.js
lib/infer/params.js
lib/sort.js
package.json
test/fixture/es6-import.output.json
test/fixture/es6.output.json
test/fixture/flow-types.output.custom.md
test/fixture/flow-types.output.json
test/fixture/flow-types.output.md
test/fixture/flow-types.output.md.json
test/fixture/html/nested.output.files
test/fixture/nearby_params.output.json
test/fixture/trailing.output.custom.md
test/fixture/trailing.output.json
test/fixture/trailing.output.md
test/fixture/trailing.output.md.json

This upstream issue is quite a doozy: https://github.com/nodejs/node/issues/4067
Possibly the only way to get around this would be to not test sorting functions in v0.10 and v0.12

Support new node versions, including v4 and v5

---

docs/GETTING_STARTED.md

Add the missed comma in GETTING_STARTED.md

---

bin/documentation.js
index.js
lib/commands/index.js
lib/commands/readme.js
package.json
test/bin-readme.js
test/bin.js
test/fixture/readme/README.input.md
test/fixture/readme/README.output.md
test/fixture/readme/index.js

Closes #261 
Chose to pull this into the codebase rather than referencing a separate `documentation-readme` package because: 
- Can share code with the `build` command
- After externalizing [`mdast-util-inject`](https://github.com/anandthakker/mdast-util-inject), it's pretty slim.
cc @tmcw

Add readme command

---

lib/flow_doctrine.js
test/lib/flow_doctrine.js

This PR adds support for string and number literal types from flow. 
Consider this example:
```js
var x: "a";
```
the relevant ast tree from flow for this would be:
```json
"typeAnnotation":{
"type":"StringLiteralTypeAnnotation",
"loc": {},
"range": {},
"value":"a",
"raw":"\"a\""
}
```
The same also works with numbers.

Add support for Flow literal string/number types

---

lib/flow_doctrine.js
test/lib/flow_doctrine.js

In my last PR #325 I forgot that there also might be boolean literal types.
These are now added. Sorry for the confusion.

Add support for flow boolean literal type

---

lib/flow_doctrine.js
lib/infer/finders.js
lib/infer/kind.js
lib/infer/membership.js
lib/infer/name.js
lib/infer/params.js
lib/input/dependency.js
lib/parsers/javascript.js
package.json
test/lib/flow_doctrine.js
test/lib/infer/membership.js
test/normalize.js
test/test.js

cc @anandthakker @jfirebaugh this passes all tests! woot. i've disabled the revealing-module pattern right now because i realized we actually aren't doing the static analysis necessary to do it safely.
Want to do a quick review and make sure this doesn't include anything truly terrible? And then we can head into the Babel 6 future.

Babel 6 upgrade, round 2

---

lib/infer/finders.js
lib/infer/params.js
lib/infer/properties.js
lib/infer/return.js
lib/is_jsdoc_comment.js
package.json

ast-types has been superseded by babel-types in this codebase.

Remove ast-types dependency

---

lib/infer/kind.js
test/fixture/es6-import.output.json
test/fixture/es6-import.output.md
test/fixture/es6-import.output.md.json
test/fixture/es6.input.js
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json
test/fixture/html/nested.input.js
test/fixture/html/nested.output.files
test/lib/infer/kind.js

Infer getters as properties, not functions

---

lib/git/url_prefix.js
package.json
test/lib/git/mock_repo.js
test/lib/github.js

`documentation` generates invalid links for GitHub Enterprise domains, because
[node-github-url-from-git](https://github.com/tj/node-github-url-from-git) returns `undefined` for such urls.
Possible solution is use `extraBaseUrls` option: https://github.com/tj/node-github-url-from-git/blob/3e20000ab2cfca0c17f6d19122e9f94135b45f98/test.js#L72
In this case github enterprise domain should be passed using additional command line option (e.g. `--github-domain`), but remote origin URL already contains needed information. Therefore I replaced [node-github-url-from-git](https://github.com/tj/node-github-url-from-git) to [git-url-parse](https://github.com/IonicaBizau/git-url-parse) (see https://github.com/documentationjs/documentation/issues/344).

support github enterprise url

---

docs/USAGE.md

It looks like the list of options in USAGE.md is not up to date. The commands are not listed, and the example lacks a command. This pull request is an attempt to fix these issues.

Add commands, update options and fix example

---

lib/filter_js.js
test/bin.js
test/fixture/extension/index.otherextension
test/fixture/extension/jsx.jsx
test/fixture/react-jsx.input.js
test/fixture/react-jsx.output.json
test/fixture/react-jsx.output.md
test/fixture/react-jsx.output.md.json

Fixes #369 
This moves the existing JSX example to confirm that our default parsing of JSX is functional, and then changes the extension test to another extension that nobody will ever use to make sure that custom extension support works.

Support js, jsx and es6 extensions by default

---

lib/infer/kind.js
lib/infer/membership.js
lib/infer/name.js
lib/parse.js
test/fixture/class.output.json
test/fixture/event.output.json
test/fixture/factory.output.json
test/fixture/inheritance.output.json
test/fixture/memberedclass.output.json
test/fixture/nearby_params.output.json
test/fixture/params.output.json
test/fixture/trailing.output.json
test/fixture/type_application.output.json
test/fixture/typedef.output.json
test/lib/infer/kind.js
test/lib/parse.js

* Set the `kind` property of the comment, not a property named by the kind.
* Set the `type` property as appropriate for these shorthands.
* Parse `@callback` as shorthand for `@typedef {Function}`
These changes bring the comment JSON into closer alignment with the [schema](https://github.com/documentationjs/documentation-schema). They also further consolidate tag-specific code in the handler map in parse.js, leaving the `infer` routines handling only AST-based inference.
cc @tmcw

More correct parsing for kind shorthand (@class, @constant, etc)

---

lib/output/html.js

- Updates html.js to not double call require when theme is set.
- Normalizes jsdoc comments.

Prevent double call to require when theme is set + jsdoc fixes

---

lib/infer/finders.js
lib/infer/name.js
test/lib/infer/name.js
test/lib/infer/params.js

This makes sure that we get the name and params from exported
functions/classes/vars.
For export default the name is inferred from the file name.
Towards #424

Pick up name and parameters from exported functions

---

lib/input/dependency.js
package.json

This PR adds experimental decorator support via the [transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy) plugin.
--
Closes #414

feat: add decorator support

---

docs/USAGE.md
index.js
lib/commands/shared_options.js
lib/infer/access.js
test/bin.js
test/fixture/infer-private.input.js
test/fixture/infer-private.output.json
test/fixture/infer-private.output.md
test/fixture/infer-private.output.md.json
test/lib/infer/access.js

This adds a command line flag called `--infer-private` which is a
string (defaults to `^_`) which is used as a regexp for inferring
if a name is private or not.
For example:
```js
/** C */
class C {
/** I'm public */
m() {}
/** I'm private */
_p() {}
}
```
Fixes #436

Add support for inferring private based on the name

---

test/bin.js
test/fixture/extension.jsx
test/fixture/extension/extension-required.jsx

`Error: Cannot find module './extension-required' from '/Users/stephencollings/workspace/documentation/test/fixture'`
According to https://github.com/documentationjs/documentation/issues/369 this should work but doesn't seem to. Any pointers anyone?
Thanks

Add failing test for .jsx dependency

---

lib/output/markdown_ast.js

When using `--config configuration.yml` with narrative sections, `documentation build -f md` crashes with `TypeError: Cannot read property 'github' of undefined` (regardless if `--github` is passed or not).
Verify that the `comment.context` object exists before reading its properties.

No context for narrative sections

---

lib/flow_doctrine.js
test/fixture/sync/flow-types.input.js
test/fixture/sync/flow-types.output.json
test/fixture/sync/flow-types.output.md
test/fixture/sync/flow-types.output.md.json
test/lib/flow_doctrine.js

Previously they were treated as optional params which is not the
same thing.

Treat flow nullable types as nullable

---

lib/infer/kind.js
lib/infer/membership.js
test/fixture/es6-import.output.json
test/fixture/es6-import.output.md
test/fixture/es6-import.output.md.json
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json

Flow/TypeScript has a special syntax for class properties. These
should be grouped under the class that they belong to.

Infer class properties

---

default_theme/section_list._
test/fixture/html/nested.output.files

This morning after updating to beta8 I discovered that when you click in a method name its description is not displayed, this PR fixes it following @anandthakker comment on https://github.com/documentationjs/documentation/issues/469#issuecomment-231231968
**Suggestion**
At this moment the chevron icon is added after the method name is clicked, it would be nice to show it by default, suggesting that there is some information that can be toggled.

Fix methods description visibility when clicked on its name

---

default_theme/section_list._
test/fixture/html/nested.output.files

As talked in https://github.com/documentationjs/documentation/pull/472, this PR shows by default a chevron icon on methods name, suggesting to the user that its content is expandable

Show chevron icon by default on methods name

---

lib/infer/name.js
test/fixture/string-literal-key.input.js
test/fixture/string-literal-key.output.json
test/fixture/string-literal-key.output.md
test/fixture/string-literal-key.output.md.json

Before this change, object properties like the one below would get the name of
a nested property:
```js
{
/**
* This node ends up getting the name 'normalKey' instead of 'string-literal-key'
*/
'string-literal-key': {
normalKey: 5
}
}
```

Infer name for string-literal property keys

---

lib/infer/name.js
test/lib/infer/name.js

If a binding name is provided we should use that in the documentation.
For example:
```js
// test.js
/** */
export default function find() {}
```
Should use the name `find` and not `test`.
Fixes #504

Use provided name for export default

---

lib/infer/kind.js
test/fixture/es6-import.output.json
test/fixture/es6.output.json
test/lib/infer/kind.js

For cases like:
```js
/** */ export class C {}
/** */ export function f {}
/** */ export const k = 42;
```
the kind did not get set properly.
Towards #484

Fix issue where exported declarations did not set the kind

---

lib/flow_doctrine.js
test/lib/flow_doctrine.js

This fixes issues with Flow tuples `[T, V]` and
Flow array types `T[]`.
Fixes #510

Handle flow tuple syntax

---

lib/infer/membership.js
test/lib/infer/membership.js

When inferring the membership of a class that is an unnamed default
export we hit a null pointer exception.
```js
export default class {
/** */
member() {}
}
```
Inferring the name for the class above fails
Fixes #506

Fix the name of infer membership for non named export default

---

lib/flow_doctrine.js
test/fixture/sync/flow-types.input.js
test/fixture/sync/flow-types.output.json
test/fixture/sync/flow-types.output.md
test/fixture/sync/flow-types.output.md.json
test/lib/flow_doctrine.js

This turns #512 into code; our test suite will judge whether we have complete flow support. cc @arv who has been doing lots of 💯 work with flow annotations.
In this branch:
- mixed: alias to `any` - this isn't exactly the Flow usage, but we also don't have a JSDoc annotation equivalent
- object: recursively turns objects into records.
- FunctionTypeAnnotation

Close gap with flow

---

lib/git/find_git.js
lib/github.js

In Node.js 6 additional assertions was added in path module:
https://github.com/nodejs/node/pull/5348

Fix github link generation for Node.js 6

---

lib/commands/build.js
test/bin-watch-serve.js

When doing `--shallow --watch` we called `generator` (which
synchronously called `updateWatcher`/`addNewFiles`) but the watcher has
not been created yet. Instead create the watcher first before
`generator` is called.
Fixes #531

Fix issue with watch and shallow

---

lib/extractors/exported.js
lib/infer/augments.js
lib/infer/finders.js
lib/infer/params.js
lib/infer/return.js
lib/infer/type.js
test/fixture/document-exported.input.js
test/fixture/document-exported.output.json
test/fixture/document-exported.output.md
test/fixture/document-exported.output.md.json

This improves detection of cases where we have:
```js
export const f = function () {};
export const o = { ... };
```
and similarly indirection using default/named.
```js
const f = function () {};
export {f};
```
Fixes #543

Handle assignments in document exported

---

lib/infer/membership.js
test/lib/infer/membership.js

Added normalization of `@memberof Foo#` and `@memberof Foo.prototype`
Added membership inference for `this.foo` inside constructor functions and class members

Membership inference improvements

---

lib/output/util/linker_stack.js
test/linker.js

Fixes #563 
Question: should custom links in configuration files win out over links to namespaces in documentation? With this PR, they would _not_ - resolution order would be:
1. Namespace
2. Configuration
3. Globals (MDN)

Fix linkerStack resolution order

---

default_theme/section._
test/fixture/html/nested.output.files

Ref: https://github.com/documentationjs/documentation/issues/469
This adds a link to all the methods of class. It is currently only generated for the whole class itself.

Show GitHub link for nested elements in default theme

---

lib/extractors/exported.js
lib/parsers/javascript.js
test/fixture/document-exported.input.js

In my use case, I have a project where imports are written without a file extension, i.e.
```js
import { foo } from './foo'; // => foo.js or foo/index.js
```
This PR uses `require.resolve` to figure out the actual file name if no extension was specified.
Most probably, a more advanced resolution would be better but this should be good enough and avoids some confusion.
Additionally, I have fixed a few problems I ran into.

Resolve imports without extension

---

lib/extractors/exported.js
test/fixture/document-exported.input.js
test/fixture/document-exported.output.json
test/fixture/document-exported.output.md
test/fixture/document-exported.output.md.json

When we find the binding for an export we get the VariableDeclarator.
It is common for people to write their JSDoc comment on the parent
VariableDeclaration so we check that in case there is no comment on the
declarator.
Fixes #570

Pick up comments on VariableDeclarations

---

default_theme/section._
test/fixture/html/nested.input.js
test/fixture/html/nested.output.files

There does not seem to be any test suite for the theme. This fixes an uncaught exception when you are using the html output with the default theme and your code has nested attributes.
i.e.
```
$ documentation build -f html -o docs
lodash.templateSources[1]:136
__e( name) +
^
ReferenceError: name is not defined
at eval (lodash.templateSources[1]:136:6)
at Array.forEach (native)
at eval (lodash.templateSources[1]:134:22)
at Array.forEach (native)
at eval (lodash.templateSources[1]:113:21)
at eval (lodash.templateSources[3]:84:11)
at Array.forEach (native)
at eval (lodash.templateSources[3]:80:7)
at /Users/cmcelligott/.nvm/versions/node/v6.9.1/lib/node_modules/documentation/default_theme/index.js:86:30
at ConcatStream.<anonymous> (/Users/cmcelligott/.nvm/versions/node/v6.9.1/lib/node_modules/ …
```

Fix ReferenceError in default theme

---

default_theme/section._
lib/output/util/format_type.js
lib/output/util/formatters.js
test/fixture/html/nested.output.files
test/fixture/nearby_params.output.md
test/fixture/nearby_params.output.md.json
test/fixture/nest_params.output.md
test/fixture/nest_params.output.md.json
test/fixture/optional-record-field-type.output.md
test/fixture/optional-record-field-type.output.md.json
test/fixture/params.output.md
test/fixture/params.output.md.json
test/fixture/sync/flow-types.output.md
test/fixture/sync/flow-types.output.md.json
test/fixture/sync/lots-of-options.output.md
test/fixture/sync/lots-of-options.output.md.json
test/format_type.js
test/lib/output/util/formatters.js

Fixes #509
Formats optionals with `?` instead of `[]`, to avoid confusion with array types.

Format optional types with ? instead of []

---

lib/output/highlighter.js
lib/output/util/formatters.js
lib/parse_markdown.js
test/bin.js
test/fixture/html/documentation.yml
test/fixture/html/nested.config-output.html
test/fixture/html/nested.input.js
test/fixture/html/nested.output.files

Port simple highlighter to run on all code snippets. cc @dignifiedquire

Highlight all Markdown, not just examples. Fixes #610

---

docs/CONFIG.md
lib/load_config.js
lib/sort.js
test/config_fixture/config_file.yml
test/fixture/snowflake.md
test/lib/load_config.js
test/lib/sort.js

feat(config): add file property for notes

---

default_theme/section._
lib/output/markdown_ast.js
test/fixture/document-exported.output.md
test/fixture/document-exported.output.md.json
test/fixture/html/nested.config-output.html
test/fixture/html/nested.output.files
test/fixture/optional-record-field-type.output.md
test/fixture/optional-record-field-type.output.md.json
test/fixture/sync/flow-types.input.js
test/fixture/sync/flow-types.output.json
test/fixture/sync/flow-types.output.md
test/fixture/sync/flow-types.output.md.json
test/fixture/sync/typedef.output.md
test/fixture/sync/typedef.output.md.json

For `typedefs`, we get `type` information on the comment but we weren't outputting it. This adds output for that type information in Markdown and HTML modes (the information was already included in JSON mode).
* Should fix #359 - cc @trodrigues

Output typedef content in Markdown and HTML. Fixes #359

---

lib/input/dependency.js
test/bin.js

This sets compact: false for babelify, so that Babel doesn't complain about not being able to
compact'ify very large files
* https://github.com/documentationjs/gulp-documentation/issues/14

fix(parser): Avoid error about deoptimization on very large files

---

bin/documentation.js

cc @arv for the review. Unfortunately I'm not seeing any way `yargs` will let us show usage examples for commands (in `documentation build --help` for instance), but this is a first step. And if this seems like a step in the right direction, we can copy/paste these examples elsewhere, like in the README.

Add more usage examples. Fixes #526

---

docs/GETTING_STARTED.md

crucial since home page links to GETTING_STARTED.md, without first showing any installation instructions -- those are currently only found in the README.md / GH repo landing page.

added missing installation instructions in GETTING_STARTED.md

---

package.json

Saves install time and space.
Refs https://github.com/documentationjs/documentation/issues/622

perf(dependencies): Move standard-changelog to devDependencies

---

README.md

node-tap removed built-in codecov support, so back to coveralls we go
Fixes https://github.com/documentationjs/documentation/issues/638

ci(coverage): Switch back to coveralls for code coverage

---

docs/NODE_API.md
lib/output/html.js
lib/output/json.js
lib/output/markdown.js

Fixes https://github.com/documentationjs/documentation/issues/642

docs(nodeapi): Fix node API documentation: formatters call (err, res)

---

default_theme/note._

Clicking on toc items generated from the documentation.yaml file didnt work. The target id was not properly slugged. Always slug your target. Very important.

Fix anchor for not toc targets

---

lib/flow_doctrine.js
lib/output/util/format_type.js
test/lib/flow_doctrine.js

If no parameter name exists in a function type, then set it to empty. Also,
fix the formatter so that `{param}: {ty}` is formatted as `{ty}` when
`{param}` is empty.
Fixes #671

Fix bug parsing anonymous closure types from Flow.

---

declarations/comment.js
lib/output/markdown_ast.js
test/fixture/meta.input.js
test/fixture/meta.output.json
test/fixture/meta.output.md
test/fixture/meta.output.md.json

Refs https://github.com/documentationjs/documentation/issues/673

feat(markdown): Add `@see` tag output in Markdown

---

test/fixture/meta.input.js
test/fixture/meta.output.json
test/lib/parse.js

The `@description` tag allows people to specify a description of a node in any place in the JSDoc
comment, instead of only at the beginning.
Fixes https://github.com/documentationjs/documentation/issues/341

test(description-tag): Confirm behavior of description tag with tests

---

lib/infer/params.js
test/fixture/params.input.js
test/fixture/params.output.json
test/fixture/params.output.md
test/fixture/params.output.md.json

Hey this is a quick fix that I needed to document my code and figured it would be appreciated upstream. Keen to hear what needs to be done to get the merged 👍 .
- documentation throws on a param of RestElement.
i.e.
```javascript
/**
* takes an array of elements and rotates the values,
* such that the first element is shifted to the end.
*/
export function rotate([ x: any, ...xs: any[] ]): any[] {
return [ ...xs, x ]
}
```
- added a code path to accomodate for such entities.

FIX: added code path for type RestElement

---

lib/extractors/exported.js

The map object provides a cleaner and more predictable way to deal with indexed data in JavaScript.
I wrote something about that here http://www.macwright.org/2017/03/13/maps-not-strictly-better.html

refactor(exported-extractor): Use Map object instead of Object.create

---

declarations/comment.js
lib/index.js
package.json

Moves index.js into lib, so it can be easily covered by our coverage tools, style linting, and so on.
Fixes https://github.com/documentationjs/documentation/issues/736

refactor: Move index.js to lib

---

default_theme/section._

Fixes #738
Can't wait to switch off of lodash-style templates so this kind of thing can be caught by the type system.

fix(html output): Fix github links in HTML output

---

lib/flow_doctrine.js
test/fixture/es6.input.js
test/fixture/es6.output-toc.md
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json
test/format_type.js
test/lib/flow_doctrine.js

Previously we naively thought that id.name would be a string for all types, which is not the case.
Instead, we use babel-generator to safely generate string representations of types.
Fixes #749

fix(flow): Fix inference of Flow types with properties

---

docs/RECIPES.md
lib/extractors/exported.js
lib/infer/params.js
lib/parsers/javascript.js
test/fixture/document-exported.input.js
test/fixture/document-exported.output.json
test/fixture/document-exported.output.md
test/fixture/document-exported.output.md.json
test/fixture/es6-class.input.js
test/fixture/es6-class.output.json
test/fixture/es6-class.output.md
test/fixture/es6-class.output.md.json
test/fixture/es6.input.js
test/fixture/es6.output-toc.md
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json

fix: Infer parameters for classes from constructors

---

docs/RECIPES.md

This tag is useful for documenting class factories in libraries and frameworks
Refs #412

docs(lends): Document the usage of the lends tag

---

lib/infer/params.js
lib/parse.js
test/fixture/es6.output-toc.md
test/fixture/es6.output.json
test/fixture/es6.output.md
test/fixture/es6.output.md.json
test/fixture/html/nested.config-output.html
test/fixture/html/nested.output.files
test/fixture/nest_params.output.json
test/fixture/nest_params.output.md
test/fixture/nest_params.output.md.json
test/fixture/params.output.json
test/fixture/params.output.md
test/fixture/params.output.md.json
test/lib/infer/params.js

* Corrects infer/params to avoid marking parameters with default as optional
* Uses lib/parse to 'massage' doctrine's optional parameters into normal parameters with default values.
Do you think this is the correct approach, or should it be handled on the output side?
Fixes #737

fix(params): Parameters with default use = not ?

---

.eslintrc
lib/infer/params.js
lib/inline_tokenizer.js
lib/parse.js
package.json
yarn.lock

test(eslint): Add eslint back to our test suite

---

docs/RECIPES.md

I got stuck by existing documentation erroring out because of the breaking change in the destructured parameters syntax. I do like the new syntax a lot better so I'd like to see the documentation reflect it.

Document new destructured parameter syntax

---

package.json
yarn.lock

The big dependencies this _doesn't_ include so far are:
* yargs: because of [this bug](https://github.com/yargs/yargs/issues/849).

chore: Upgrade dependencies that don't break everything

---

__tests__/fixture/simple-callback.input.js
src/default_theme/index.js

Test doesn't seem to get run because of #817

Decorate callbacks

---

__tests__/lib/lint.js
declarations/comment.js
src/lint.js
src/nest.js

Check on parent element: foo.bar sub-parametr should be documeted with parent.
Fixed #832 issue

Included nest module to the lint documentation.

---

__tests__/lib/merge_config.js
src/merge_config.js

The first priority from CLI(from user) settings then package.json.
Fixed #845

Merging configs should be by prioritize.

---

__tests__/lib/flow_doctrine.js
src/flow_doctrine.js

Without this, class methods that return `this` were showing up in generated output as returning `any`.

Add support for converting flow’s ThisTypeAnnotation to a doctrine NameExpression

---

docs/NODE_API.md
src/output/html.js
src/output/markdown.js

Make html and markdown second option is optional

---

.babelrc
circle.yml
docs/NODE_API.md
package.json
src/output/html.js
src/output/markdown.js

Supporting this syntax uncorks a whole bottle of worms and requires participation in more of the
JavaScript ecosystem and is not worthwhile in my opinion at this time.
Fixes #873

style: Avoid optional parameter syntax

---

src/commands/readme.js
src/default_theme/assets/anchor.js
src/extractors/comments.js
src/filter_access.js
src/github.js
src/input/shallow.js
src/is_jsdoc_comment.js
src/lint.js
src/module_filters.js
src/nest.js
src/output/markdown.js
src/parse.js
src/parsers/javascript.js
src/sort.js

For consistency purposes makes sense to use the same tag for defining return values.

Making return type params consistent with the rest of the code base

---

__tests__/lib/infer/params.js
__tests__/lib/parse.js
declarations/comment.js
src/infer/params.js
src/parse.js
src/parsers/javascript.js

[Per usejsdoc.org](http://usejsdoc.org/tags-hideconstructor.html), this tag goes either in a comment attached to a function that has declared that function to be a class, or in a comment on an ES6 class constructor.
This is relevant to the discussion in #689.

feat: implement @hideconstructor

---

__tests__/__snapshots__/bin.js.snap
__tests__/__snapshots__/test.js.snap
__tests__/fixture/html/nested.input.js
src/default_theme/index._
src/default_theme/index.js
src/default_theme/paramProperty._
src/default_theme/section._
src/default_theme/section_list._

Hello,
I ran into an issue where certain portions of the JSON output was not being included in the HTML output. Specifically, properties underneath parameter properties (`section.params.properties.properties`). These sub-properties are included in the MD output, so I assumed they should be part of the HTML output. So here's my fix.
```
// testFile.js
/**
* Documentation for some function.
* @name testFunction
* @param {Object} options An options parameter.
* @param  {Object} options.firstLevelOne A property of the options parameter.
* @param  {Boolean} options.firstLevelOne.secondLevelOne A second level property.
* @param  {Boolean} options.firstLevelOne.secondLevelTwo A second second level property.
* @param  {Boolean} options.firstLevelTwo A second first level property.
*/
export …
```

HTML output: Display all levels of parameter properties.

---

src/default_theme/assets/site.js

Previously this was calculated so that the left page would expand to its natural size. That's not
really what we want, because the natural size could be as high as 100%.
Fixes #927

fix: Fix the split in HTML at 33/67% instead of calculating percentages

---

__tests__/__snapshots__/bin-readme.js.snap
__tests__/__snapshots__/bin.js.snap
__tests__/__snapshots__/test.js.snap
__tests__/format_type.js
__tests__/linker.js
docs/NODE_API.md
package.json
yarn.lock

This allows the Mozilla Developer Network to infer the user language.
Fix #964

fix(globals-docs): Remove en-US from MDN links.

---

README.md
docs/USAGE.md

Updated the help command and it's output in the readme and usage files.

docs(readme, usage): updated help command/message

---

.npmignore

Seems like `.npmignore` was not updated after Jest was introduced and now `__tests__` are the part of the package in NPM: https://unpkg.com/documentation@5.3.5/

Fix .npmignore for tests folder

---

src/infer/params.js
src/parsers/javascript.js

My main motivation for this was that VSCode intellisense does not work when constructor params are defined at the class declaration, it expects them at the constructor. 
So I just merged the params from a constructor comment during the infer phase. 
Relevant issue: https://github.com/documentationjs/documentation/issues/689
This was my first look into this code and I couldn't get the build to work locally let alone the tests so I'm hoping the tests can be checked in circle. 
Edit: Just to clarify, I did actually test that it did what I wanted to by editing my local node_module/documentation/lib files directly. I was getting flow type syntax errors on build and I'm not very familiar with flow so this was the easiest way for me to work with it.

Add support for class param declarations at the constructor

---

src/input/dependency.js
src/merge_config.js

Fixes https://github.com/documentationjs/documentation/issues/1022.
`.mjs` is ordered before `.js` as that is the resolution order in other tools such as Webpack v4.

Support the .mjs extension by default.

---

docs/THEMING.md

Add instructions to effectively fork the default theme for the purpose of creating and using your own custom theme.

Docs: Update THEMING.MD

---

__tests__/lib/github.js
declarations/comment.js
src/github.js

Unlike other comment blocks, `@typedef` blocks are usually not directly associated with any lines of code.
eg, from [usejsdoc](http://usejsdoc.org/tags-typedef.html):
```javascript
/**
* A number, or a string containing a number.
* @typedef {(number|string)} NumberLike
*/
/**
* Set the magic number.
* @param {NumberLike} x - The magic number.
*/
function setMagicNumber(x) {
}
```
Currently, the github link that's produced for a `@typedef` block points to the nearest AST node, which would be the `function` in this case. This change uses the comment block's location instead.

Fix github links for @typedef comments

---

package.json
src/serve/server.js
yarn.lock

After a release containing this commit is rolled, documentation.js will
go to 6.x and will require Node > 6.x
Fixes #1014

fix: Make documentation.js compatible with node 4.x for one more version

---

.babelrc
__tests__/lib/infer/kind.js
package.json
src/serve/server.js
yarn.lock

BREAKING CHANGE: documentation.js requires node v6 or newer.

feat: documentation.js now requires node v6 or newer.

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/lends.input.js
src/infer/membership.js

Good day,
This MR closes #840
At the moment if object property key is a literal it will not be processed correctly because conditions check for `NodePath.isIdentifier()`.

fix: lends with object property using literal key 

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/es6-class-property.input.js
src/parse.js

This adds support for `@type {SomeType}` on getters and setters, similar to what JSDoc has.
This was already reported as #906.

Support class property @type tag

---

__tests__/__snapshots__/bin.js.snap
__tests__/__snapshots__/test.js.snap
__tests__/bin.js
__tests__/test.js

Our tests test _against_ documentation.js itself. Which is neat, but has the disadvantage that they include the version number of documentation.js, so every time that we release a version, the tests break because the version number doesn't match.
This PR that I should have written a long time ago sanitizes that version number, so tests continue to pass even when we release new versions.

test: Make tests resilient between versions: no more annoying chores

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/es6.input.js
src/infer/finders.js

Previously we did not properly infer params on methods that were located on class properties. This
changes things so that we do. It carefully tries to avoid messing up the existing support of class
type annotations, which are similar to class properties at the AST level, but do not have an
associated node, only a type alias.
Fixes #1043

feat(inferTypes): Support class properties

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/es6.input.js
package.json
yarn.lock

Support decorators is an unspecified part of JSDoc: we're just going forward and implementing a new
syntax here because it's unlikely that JSDoc will move fast enough.
Fixes #1016

feat(doctrine): Support decorator syntax in examples

---

__tests__/lib/input/dependency.js
package.json
src/smart_glob.js
yarn.lock

This is #1044 rebased on top of #1045 to fix tests.

fix: get rid of shelljs dependency

---

__tests__/__snapshots__/test.js.snap
__tests__/test.js
src/index.js

fix: adding vue support broke tests that are not file based

---

package.json
src/commands/shared_options.js
src/output/util/format_type.js
src/sort.js
yarn.lock

chore(package): update flow-bin to version 0.71.0

---

__tests__/fixture/flow/comment-types.js
__tests__/lib/parsers/parse_to_ast.js
src/parsers/parse_to_ast.js

This PR adds support for flow comments types (see #306, #386 and #586) by converting them into regular flow annotations before passing the source on to babylon.
Code that does not include the `@flow` pragma is left untouched.

feat: support flow comment types

---

__tests__/__snapshots__/bin.js.snap
__tests__/__snapshots__/test.js.snap
__tests__/lib/merge_config.js
docs/USAGE.md
src/commands/shared_options.js
src/default_theme/index._
src/merge_config.js

This pull request integrates that it is possible to add a project description (fix: #1039). This will be default inherit from the `package.json` and can be optional given by the `--project-description` flag. Currently it is only used as a meta description for SEO (Google, ...). But I think it also makes sense to add it to the default template and position it under the header like that:
But that's not yet implemented in this PR.

feat: added project description (fix: #1039)

---

__tests__/lib/infer/membership.js
src/infer/membership.js

This PR resolves #1121.
Improve inferMembership to allow to use next code:
```js
/**
* @memberof BigFeature
*/
class MyClass {
/** method */
method() {}
}
```
Before this improvement, we have `method` inside
`global.MyClass` instead of `global.BigFeature.MyClass`

Fix membership infering for methods

---

package.json
yarn.lock

This fixes an issue where a dependency of `chokidar` (`upath`) does not support node versions greater than 9. This was fixed in `upath v1.0.5` which was subsequently bumped in `chokidar v2.0.4`.
Reference: https://github.com/anodynos/upath/pull/15

Bumping dependency for Node 10 support

---

__tests__/lib/infer/properties.js
src/infer/properties.js

Fixing issue mentioned in this comment: https://github.com/documentationjs/documentation/issues/843#issuecomment-318009351
When property is declared in comment for type definition, its duplicated by inferred property - code handling this was already there, but checking if property name is present in the set was broken.

fix: inferred properties duplicating explicitly specified ones

---

__tests__/__snapshots__/test.js.snap
docs/USAGE.md
src/commands/shared_options.js
src/default_theme/index._

Adds support for setting the favicon in the html output.

feat: Add favicon option

---

package.json
yarn.lock

Fixes #1209 by restricting to only good new versions.

chore(deps): Bump highlight.js to known working version

---

package.json
yarn.lock

Removes potential security vulnerability:
https://snyk.io/test/npm/yargs/9.0.1

chore(deps): update yargs to 12.0.2

---

declarations/comment.js
docs/USAGE.md
src/commands/shared_options.js
src/output/markdown_ast.js

I'm adding an additional cli option, `markdown-toc-max-depth` for configuring the plguin,`markdown-toc`'s `maxDepth` argument. This is useful if we want to control the depth of the `table of content`.
This shouldn't introduce any regression because it's just an extra configuration on top of `markdown-toc`.
I'm unfamiliar with writing tests for this particular kind of stuff . Therefore, I was only able to confirm manually. I would be more than happy to include some tests if someone want to lend me a hand. :)
Address #1101

Adding markdown-toc-max-depth

---

src/commands/shared_options.js
src/input/dependency.js

**Proposal:**
Allow users to support their own babel configuration via new cli option:
```
documentation build --babel=./babel.config.js
```
Aims to resolve: https://github.com/documentationjs/documentation/issues/1149, https://github.com/documentationjs/documentation/issues/140
This will need some refinement of implementation, but if the overall concept is acceptable, that should be easy to resolve.

Support custom babel config

---

docs/RECIPES.md

It may be worth mentioning how promises are documented as they have become a widely used feature of JavaScript. It took me a while of searching through issues to find issue #104 which comments on the correct way to document them.

Added promises to "recipes" documentation

---

docs/THEMING.md

Now 
> In the folder you created, replace require('../') on lines 10 and 11 of index.js with require('documentation') and save.
ref: https://github.com/documentationjs/documentation/blob/64ef671d993922821daf8e18d7dc28cdeaa1614a/docs/THEMING.md#customizing-the-default-theme
`10 and 11 of index.js` should be `8 and 9 of index.js`.

THEMING.md line number is incorrect

---

__tests__/lib/infer/__snapshots__/params.js.snap
__tests__/lib/infer/params.js
src/infer/params.js

Merge explicit and inferred param defaults

---

src/parsers/parse_to_ast.js

Add support for exportNamespaceFrom plugins in parser
issues #1238

feat: Support exportNamespaceFrom in parser

---

src/commands/build.js

yargs now variadic positional arguments undefined instead of []
Fixes #1259

fix: Crash when called with no inputs. 

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/es6.input.js
src/infer/params.js

fix: Allow skipped array arguments in destructuring

---

__tests__/lib/git/find_git.js
__tests__/lib/git/url_prefix.js
__tests__/utils.js
src/git/url_prefix.js

Fixes git submodule handling for repos containing `.` in the name. Addresses https://github.com/documentationjs/documentation/pull/1270#discussion_r309464612

fix: Git submodule support for repo names with a dot

---

src/ts_doctrine.js

Alright, this is just an one-liner simply fixing a patch but that's the easiest thing I can do with our keybase-bot codebase.
The following command triggers the crash when you run it on keybase-bot:
```
documentation.js readme 'src/**/*.ts' --config documentation.yml --require-extension=.ts --parse-extension=.ts --section=API --shallow
```
This is totally unrelated to another bug which happens when you run it without `shallow`:
```
documentation.js readme 'src/**/*.ts' --config documentation.yml --require-extension=.ts --parse-extension=.ts --section=API
```
I have no clue what ts_doctrine's output means and how to work with it so I went with the simplest fix. Unfortunately that still doesn't fix most of our issues but at least it generates docs without crashing.
Related to #1260

Fix a crash in ts_doctrine.js

---

src/commands/readme.js

Compare to the result of the latest diff module: https://runkit.com/embed/y4qzdzzz05qr
No diff currently gives this result:
```
Index: 
===================================================================
--- 	
+++ 	
```
But the current check expect it to result in an empty string, causing the `--diff-only` flag in the readme CLI to fail.

Fix check for empty diff

---

docs/FAQ.md

HTTPS link to https://eslint.org/docs/rules/valid-jsdoc.html

---

.npmignore

I added more files to `.npmignore` to keep `node_modules` small

Reduce npm package by removing development files

---

package.json
yarn.lock

Fixes #1320 and will imbue documentation.js with the slimmer/better new chokidar 3.
Also runs `yarn update` because otherwise `sane` and `fsevents` and `node-gyp` are making a fuss. That won't affect downstream users because usage of documentation.js as a dependency doesn't use locks.

deps: Update chokidar, bump yarn.lock

---

src/infer/properties.js

Fixes an issue where documentationjs breaks on build when  using object
spread and Flow utility $Exact (i.g: ...Exact<Type>)
✅ Closes: #1324

fix: 🐛 Fixes an issue when using object spread and $Exact

---

__tests__/__snapshots__/test.js.snap
__tests__/lib/infer/type.js
src/infer/type.js

When an object is flow typed, a `type` AND `properties` section is
rendered. The type section seems redundant and isn't formatted, whereas
the properties section is. This PR removes the `type` section when
dealing with an object type.
✅ Closes: #1326

refactor: 💡 type section is redundant and not formatted

---

src/default_theme/index.js

This is another particular corner where we made an unsafe assumption that `section.type` existed, so in the case where it was null but kind was typedef, crash.

fix: Additional safety around detecting functions in HTML output

---

README.md

Thanks to @SantoJambit for pointing out in #1272 the need for the `--parse-extension ts` argument to build docs for TypeScript projects.

Add TypeScript usage example

---

docs/THEMING.md

Added content about an alternative way to make style changes without recreating an entire new theme that needs to be pulled in as a separate node module or even a separate repository.
There are a couple reasons I can imagine this isn't best practice. There are likely additional reasons.
However, it has so much "easy and just works" quality, that I figured I'd share.

An alternative way to make style changes to html output without recreating an entire new theme via documentation.yml

---

package.json
src/parsers/vue.js
yarn.lock

Vue dependencies was moved to optionalDependencies
So, that mean if you need Vue support you also have to add in own package.json
new dependency for Vue 2 is vue-template-compiler, Vue 3 is @vue/compiler-sfc

fix: add support Vue 3 fixed #1339

---

src/input/dependency.js
src/parsers/parse_to_ast.js

ts has conflict syntax with casting type. It is valid TS but not valid TSX

fix: jsx should be included for tsx files but not for ts fixed #1359

---

__tests__/__snapshots__/test.js.snap
__tests__/fixture/html/nested.input.js
__tests__/lib/parse.js
__tests__/lib/parsers/javascript.js
package.json
src/remark-jsDoc-link.js
src/remark-parse.js
src/remark-remove-position.js
yarn.lock

Plugins for remark was reworks because @link should be catch by first then autolink

fix: add gfm format for remark fixed #1374

---

src/commands/readme.js

When '.' does not work, this utility function outside the runtime closure can yield an unhelpful error for consumers.

fix: use process.cwd vs `.` which can fail

---

__tests__/lib/__snapshots__/sort.js.snap
src/sort.js

This PR fixes sorting of undefined values - before they were randomly intermingled inbetween the rest because `1 < undefined === false` && `1 > undefined === false`
Normally, no element should have an undefined `kind` - this PR simply moves them all to the top where they will be immediately seen

correctly sort undefined values

---

README.md

An outbound link to JSDoc was [broken](https://usejsdoc.org/about-getting-started.html). updated with an [active link](https://jsdoc.app/about-getting-started.html)

Broken External Link

---

package-lock.json
package.json

The 5.1.3 patch version introduced a bug related to BigInt that breaks the test, so we jump directly to 5.1.4

Bump mock-fs from 5.1.2 to 5.1.4

---

.github/dependabot.yml
.husky/pre-commit
package-lock.json
package.json

We were on husky 4 because husky 5 changed the license away from MIT. The licence got changed back to MIT in husky 6 and forward, so now we can got up to date with a migration to husky 8.
There is a [migration cli](https://github.com/typicode/husky-4-to-8) from husky 4 to 8 that was used.

run migration script from husky 4 to 8

---

LICENSE
package-lock.json
src/parsers/parse_to_ast.js

I was struggling to use Documentation.js with some newer ES2020 features (like private class properties), I ended up forking Documentation.js and adding the Babel plugin list from Prettier. I also bumped Babel versions to latest.
https://github.com/prettier/prettier/blob/24d39a906834cf449304dc684b280a5ca9a0a6d7/src/language-js/parser-babel.js#L23
Hopefully given the size of Prettier, this would allow for easier maintenance in the future.
To stay on the correct side of the MIT License, I added Prettier's LICENSE to this LICENSE file.
---
This PR, and bumping the versions, ended up with a **very** large `package-lock.json` change. I assume this is okay since other than the new Babel versions, I used `npm ci`?
Please let me know if I could change it to make the diff smaller

feat: :sparkles: update Babel, copy list of plugins from Prettier

---

package-lock.json
package.json

Fixes: https://github.com/documentationjs/documentation/issues/1558
Signed-off-by: Lance Ball <lball@redhat.com>

chore: upgrade git-url-parse to 13.1.0

---

.github/workflows/node.js.yml
package.json

Node 14 and 16 are both EOL: https://nodejs.org/en/about/previous-releases
This removes them from the test matrix and makes the minimum engines requirement 18.

Stop testing in Node 14 and 16
