documentationjs/documentation

- package.json
- share/html.hbs
- streams/output/html.js
> Begin HTML support. Fixes #2

- streams/infer_name.js
- test/fixture/event.output.custom.md
- test/fixture/event.output.json
- test/fixture/event.output.md
- test/fixture/factory.output.custom.md
- test/fixture/factory.output.json
- test/fixture/factory.output.md
- test/fixture/optional.output.custom.md
- test/fixture/optional.output.json
- test/fixture/optional.output.md
> Support name inference from class and event tags

- .eslintrc
- bin/documentation.js
- lib/args.js
Closes #154 
cc @tmcw; also: any strong feelings about the lint setting I added?
> Pull additional parsing and validation into args.js

- lib/infer/params.js
- lib/output/markdown_ast.js
- test/fixture/class.output.custom.md
- test/fixture/class.output.md
- test/fixture/class.output.md.json
- test/fixture/event.output.custom.md
- test/fixture/event.output.md
- test/fixture/event.output.md.json
- test/fixture/html/nested.output.files
- test/fixture/nested_properties.output.custom.md
- test/fixture/nested_properties.output.md
- test/fixture/nested_properties.output.md.json
- test/fixture/param_nest.input.js
- test/fixture/param_nest.output.custom.md
- test/fixture/param_nest.output.json
- test/fixture/param_nest.output.md
- test/fixture/param_nest.output.md.json
- test/fixture/typedef.output.custom.md
- test/fixture/typedef.output.md
- test/fixture/typedef.output.md.json
> Fix parameter sorting, nest properties in Markdown

- lib/infer/params.js
- lib/output/markdown_ast.js
- test/fixture/default-param.input.js
- test/fixture/default-param.output.custom.md
- test/fixture/default-param.output.json
- test/fixture/default-param.output.md
- test/fixture/default-param.output.md.json
- test/fixture/flow-default.input.js
- test/fixture/flow-default.output.custom.md
- test/fixture/flow-default.output.json
- test/fixture/flow-default.output.md
- test/fixture/flow-default.output.md.json
- test/fixture/optional.output.custom.md
- test/fixture/optional.output.md
- test/fixture/param_nest.output.custom.md
- test/fixture/param_nest.output.md
- test/fixture/param_nest.output.md.json
cc @killercup this implements default parameter parsing for both
flow-annotated and unannotated methods
> Add and test default parameter parsing. Fixes #168

- bin/documentation.js
- lib/format_error.js
- lib/hierarchy.js
- lib/lint.js
- lib/nest_params.js
- test/fixture/_external-deps-included.json
- test/fixture/_multi-file-input.json
- test/fixture/factory.output.json
- test/fixture/inline-link.output.json
- test/fixture/jsx.output.json
- test/fixture/memberof-missing.output.json
- test/fixture/memberof-no-scope.output.json
- test/fixture/multiexample.output.json
- test/fixture/newline-in-description.output.json
- test/fixture/simple-hashbang.output.json
- test/fixture/simple-two.output.json
- test/fixture/simple.output.github.json
- test/fixture/simple.output.json
- test/fixture/throws.output.json
- test/lib/error.js
- test/lib/hierarchy.js
- test/lib/lint.js
- test/lib/nest_params.js
> Store commentLineNumber on errors. Fixes #159

- lib/infer/membership.js
- test/fixture/_external-deps-included.json
- test/fixture/_multi-file-input.json
- test/fixture/inline-link.output.custom.md
- test/fixture/inline-link.output.json
- test/fixture/inline-link.output.md
- test/fixture/inline-link.output.md.json
- test/fixture/jsx.output.custom.md
- test/fixture/jsx.output.json
- test/fixture/jsx.output.md
- test/fixture/jsx.output.md.json
- test/fixture/multiexample.output.custom.md
- test/fixture/multiexample.output.json
- test/fixture/multiexample.output.md
- test/fixture/multiexample.output.md.json
- test/fixture/simple-hashbang.output.custom.md
- test/fixture/simple-hashbang.output.json
- test/fixture/simple-hashbang.output.md
- test/fixture/simple-hashbang.output.md.json
- test/fixture/simple.output.custom.md
- test/fixture/simple.output.github.json
- test/fixture/simple.output.json
- test/fixture/simple.output.md
- test/fixture/simple.output.md.json
- test/lib/infer/membership.js
> Correctly name comments attached to module.exports (fixes #178)

- .eslintignore
- .eslintrc
- package.json
- streams/input/README.md
- streams/output/README.md
- test/.eslintrc
- test/fixture/infer-params.input.js
- test/fixture/infer-params.output.json
> Modernize eslint configuration, customize eslint for tests

- lib/input/dependency.js
- lib/parsers/javascript.js
- test/fixture/es6-import.output.custom.md
- test/fixture/es6-import.output.json
- test/fixture/es6-import.output.md
- test/fixture/es6-import.output.md.json
- test/fixture/es6.input.js
- test/fixture/es6.output.custom.md
- test/fixture/es6.output.json
- test/fixture/es6.output.md
- test/fixture/es6.output.md.json
> Support ES7 class properties

- lib/parsers/javascript.js
- package.json
- test/fixture/bad/syntax.output.json
- test/fixture/es6-import.output.custom.md
- test/fixture/es6-import.output.json
- test/fixture/es6-import.output.md
- test/fixture/es6-import.output.md.json
- test/fixture/es6.input.js
- test/fixture/es6.output.custom.md
- test/fixture/es6.output.json
- test/fixture/es6.output.md
- test/fixture/es6.output.md.json
- test/test.js
Fixes #201 - this turns on all stage 0 babel features
> Try using babel-core to support stage 0

- lib/git/url_prefix.js
- test/lib/git/find_git.js
- test/lib/git/mock_repo.js
- test/lib/git/url_prefix.js
- test/lib/github.js
> Fix and test detached url prefixes. Fixes #251

- lib/infer/params.js
- test/fixture/es6-import.output.custom.md
- test/fixture/es6-import.output.json
- test/fixture/es6-import.output.md
- test/fixture/es6-import.output.md.json
- test/fixture/es6.input.js
- test/fixture/es6.output.custom.md
- test/fixture/es6.output.json
- test/fixture/es6.output.md
- test/fixture/es6.output.md.json
- test/fixture/infer-params.output.custom.md
- test/fixture/infer-params.output.json
- test/fixture/infer-params.output.md
- test/fixture/infer-params.output.md.json
> Improve parameter inference for destructuring and defaults

- lib/infer/augments.js
- lib/infer/finders.js
- lib/infer/params.js
- lib/infer/properties.js
- lib/infer/return.js
- test/fixture/inheritance.input.js
- test/fixture/inheritance.output.custom.md
- test/fixture/inheritance.output.json
- test/fixture/inheritance.output.md
- test/fixture/inheritance.output.md.json
> Avoid traversal where possible. Fixes #293

- bin/documentation.js
- index.js
- lib/commands/build.js
- lib/commands/index.js
- lib/filter_access.js
- test/bin.js
- test/lib/filter_access.js
cc @jfirebaugh for the review
@thejameskyle this will permit for `--access=public`
> Add --access flag. Fixes #262

- lib/lint.js
- lib/output/html.js
- test/fixture/empty-example.input.js
- test/fixture/empty-example.output.json
- test/fixture/empty-example.output.md
- test/fixture/empty-example.output.md.json
Also I added lint rule.
What branch should I use for pull-request?
> Fix throwing error when "example" tag is empty

- index.js
- lib/filter_js.js
- test/bin.js
- test/fixture/polyglot/blend.json
> Fix overeager JS filtering in polyglot mode.

- test/lib/hierarchy.js
It could be a bit verbose, let me know what do you think.
> Add test for Object.prototype member's name

- lib/infer/finders.js
- lib/infer/name.js
- test/fixture/params.output.json
- test/fixture/params.output.md
- test/fixture/params.output.md.json
- test/lib/infer/name.js
- test/lib/infer/params.js
Updating test fixtures for #435
> Arv exported functions

- lib/output/util/formatters.js
- test/lib/output/util/formatters.js
@tmcw As with #470, this is a pretty straightforward fix, but I'll wait on your review.
> Fix short signatures for inferred params

- lib/commands/serve.js
- lib/serve/server.js
- test/bin-watch-serve.js
- test/lib/server.js
> Allow the user to specify port.

- default_theme/index.js
- lib/output/util/formatters.js
- lib/output/util/linker_stack.js
Rebased and fixed up version of #463
> Robertleeplummerjr master

- test/fixture/document-exported.output.json
The test file needed an update after #503
> Update test expectations

- lib/output/util/formatters.js
This allows custom themes to override it
> Expose formatParameter as a formatter

- bin/documentation.js
- default_theme/test/format_markdown.js
- default_theme/test/index.js
- lib/commands/build.js
- lib/commands/lint.js
- lib/commands/readme.js
- lib/commands/serve.js
- lib/commands/shared_options.js
- lib/lint.js
- lib/parse_markdown.js
- lib/serve/server.js
- package.json
- test/bin.js
- test/fixture/html/nested.output.files
- test/fixture/lint/lint.output.js
- test/lib/parse.js
- test/lib/parsers/javascript.js
- test/lib/parsers/polyglot.js
Updates to new versions of yargs and remark and refactors to use more of yarg's nice API rather than bin/documentation.js kludge.
> [wip] Update yargs

- test/fixture/es6-import.output.json
- test/fixture/es6-import.output.md
- test/fixture/es6-import.output.md.json
- test/fixture/es6.input.js
- test/fixture/es6.output.json
- test/fixture/es6.output.md
- test/fixture/es6.output.md.json
> Add regression case for #498

- lib/infer/return.js
cc @arv for the review, this is a follow-up to #604
> Check length before assigning to a return tag

- package.json
Misc edits; moved the magic section higher up. It's too important to be left at the end.
> Style fixes and edits.

- package.json
Fixes https://github.com/documentationjs/documentation/issues/715
> chore(standard-version): Use standard-version to release new versions

- test/format_type.js
> test(format_type): Test formatting of string enums

- ISSUE_TEMPLATE.md
> docs: Add issue template

- __tests__/__snapshots__/test.js.snap
- __tests__/test.js
> test: Run input tests

- .babelrc
- __tests__/__snapshots__/bin.js.snap
- __tests__/__snapshots__/test.js.snap
- src/default_theme/assets/anchor.js
- src/default_theme/assets/bass.css
- src/default_theme/assets/site.js
- src/default_theme/assets/split.css
- src/default_theme/assets/split.js
- src/default_theme/assets/style.css
- src/default_theme/index._
Rebased & squashed version of #858
> feat(theme): Flexible sidebar for default theme

- __tests__/lib/__snapshots__/sort.js.snap
- __tests__/lib/sort.js
- src/sort.js
> Fixed alphabetical sort and add flow notation to sort file

- .babelrc
Fixes https://github.com/documentationjs/documentation/issues/888
> Fix default_theme JS bug

- __tests__/fixture/es6-import.input.js
- src/parsers/parse_to_ast.js
> fix: Enable dynamicImport plugin to support import() syntax

- package.json
- yarn.lock
> chore(package): update jest to version 22.1.2

- package.json
- yarn.lock
> chore(package): update flow-bin to version 0.63.1

- package.json
- yarn.lock
> chore(package): update flow-bin to version 0.66.0

- declarations/comment.js
- package.json
- src/serve/error_page.js
- yarn.lock
> chore(package): update flow-bin to version 0.69.0

- package.json
- yarn.lock
> chore(package): update fs-extra to version 6.0.1

- __tests__/bin-watch-serve.js
- src/commands/serve.js
Update serve command to pass object to get-port
Closes #1119
> Update test for serving on specified port.

- src/default_theme/index._
> HTTPS link

- __tests__/__snapshots__/test.js.snap
- src/default_theme/index._
- src/default_theme/section._
Fix notes also showing up as duplicate sections. (fixes #1113)
**Before:**
**After:**
> fix(default theme): only render either note or section (fixes #1113)

- src/parsers/parse_to_ast.js
> Add classPrivateProperties as babelParser options

- __tests__/__snapshots__/test.js.snap
- __tests__/fixture/flow-unnamed-params.input.js
- __tests__/lib/infer/__snapshots__/params.js.snap
- src/infer/params.js
> fix: Fix parsing of optional parameters with annotations

- src/default_theme/index._
This removes the unnecessary trailing slash from the HTML theme.
> remove unnecessary trailing slash

- src/default_theme/index._
- src/default_theme/note._
> fix toc with children getting displayed as "note"

- src/default_theme/assets/style.css
REF: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA6AJhMBXAtgmAQxgEtoACYAHSnPIDNoYBaew3EgGwE8lyAJOJwBucUmEIAacgGdCUGcxlwATiXoBuGnUicIKvgGIAbKa21ynElDjMAFnBIBzOzD4BGVAFZzdAEaEYADWTioQ2FDoRvReMTHmAL40NKh+nIFBlNrkuvpGpsaJyVCpTswA7nYk8FkWAcGh4ZHMuQbkhvSdRVA0dgAstXS4hCpO1nwATAAMAA4AHuRT5O6zC1PdKZg4+LDEZLR2AMyDORB6bYZTVxslfvroqsx3MDAQuCd3Kg8qLWd57ehATdCCdWkZ3O4ABx9ADCAFFfOR4HMWA9ICo9tA+FBoHAbhgsHgCJjaIQANp2FRwegAXSQdggohUJ2RqLg6JJfAi3ysNmB9MZqlB2BUMn+Mwg1ngKnxM247mY2E4lhIJxmhEB1icfC880W+OGc3sjhcLBWS2oFkNxucrg8VwApPiHLaWMISHByhKVGaricXab7VNhHYbsowKQsURRmJyEcToxYBUTXaAOzXGhJHolLZE3aR2gwdCSTaEnZEAtIuwnOjqzVQbXkVATLxU97N1twXA3OzuAVMpvyMAMlQAK0UvKCJagdgm-aFqCHI-HzEn06O8+Zi6gw-0K7XvT6m8HO+XE+smUtdAg6rA1V4y3x9BIRuOV-I5RI6BgdkmXid2TWp+36-uQEx9H08xPi+zBvtkwE-n+AFWoQRoIaB4GQXMNwAAL4OgJAggAFBwUAVF+iHk …
> Formatted style.css with Prettier

- .editorconfig
> editorconfig rules should apply to CSS too

- package.json
- yarn.lock
> fix: upgrade git-url-parse to fix a parsing issue

- docs/GETTING_STARTED.md
> update jsdoc.app URL in GETTING_STARTED.md

- __tests__/__snapshots__/test.js.snap
- __tests__/fixture/meta.input.js
- __tests__/lib/parse.js
- src/default_theme/section._
- src/output/markdown_ast.js
- src/parse.js
> Add see ref to html

- __tests__/__snapshots__/test.js.snap
- __tests__/fixture/nest_events.input.js
- src/output/markdown_ast.js
This PR adds class events to the markdown output.
The events are already in html output.
> Add event members to md output

- yarn.lock
Routine update of yarn.lock to make sure that semver ranges are still valid.
> Dependency update bumps

- package.json
- yarn.lock
> Update highlight.js to the version 10.

- __tests__/bin-readme.js
- __tests__/lib/infer/access.js
- __tests__/lib/merge_config.js
- __tests__/test.js
- package.json
- src/config.js
- src/merge_config.js
- src/parsers/parse_to_ast.js
- yarn.lock
It will be easy to not put config as parameter each time
> refactor: use singleton config for execution

- __tests__/fixture/sort-order-alpha.input.js
- __tests__/lib/__snapshots__/sort.js.snap
- __tests__/lib/sort.js
- docs/USAGE.md
- src/commands/shared_options.js
- src/sort.js
This PR adds support for specifying multiple sorting orders and also for sorting by object kind (function, variable, class...)
> support additional sorting orders

- __tests__/__snapshots__/bin.js.snap
- __tests__/__snapshots__/test.js.snap
- __tests__/fixture/html/nested.input.js
- src/default_theme/index.js
Keep track of generated slugs to always guarantee that they are unique
Refs: #1477
> always generate unique hash ids

- .github/dependabot.yml
> update Dependabot docs link

- README.md
This domain has been offline for a few years.
> Remove broken David badge on README

- package-lock.json
> Fix outdated deps
